name: test

on:
  repository_dispatch:

env:
  OPENWRT_SOURCE_URL: https://github.com/istoreos/istoreos.git

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout 初始化环境
      uses: actions/checkout@main
      
    - name: download 下载Openwrt
      run: |
        git clone $OPENWRT_SOURCE_URL openwrt
        cd openwrt
        ls
      
