
name: test
on: workflow_dispatch

env:
  AAA: "你好"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - name: 创建文件
        run: |
          mkdir aaa
          touch ./aaa/abcd
          cat ./aaa/abcd
