name: test2
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - name: 读取本地仓库测试
        run: |
          [ -e .config ] && mv .config .config
          ls
        
