
name: test
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - name: 创建文件
        run: |
          mkdir aaa
          touch ./aaa/abcd
          echo '你好' > ./aaa/abcd
          cat ./aaa/abcd
      - name: 上传文件夹
        uses: actions/upload-artifact@main 
        with:
          name: my-artifact
          path: ${{ github.workspace }}/aaa

